### ISSUE TITLE
create a full pip installable package.

### ISSUE THREAD

**Issue by TonyFlury** [csurfer/pyheat#1]
It should be possible to create this as full package installable from pip without needing to resort to cloning the git repository.

**Comment by csurfer** [comment]
@TonyFlury : Made it python3 compatible and a pip installable. You can install the package now using `pip install py-heat`. Thanks for the push :). I was being lazy !

**Comment by bhaveshmunot1** [comment]
After installation : error pyheat command not found

**Comment by arinbjornk** [comment]
@csurfer regarding python3 compatibility: I installed it using pip3 but I'm unable to make it run on a python3 file.

**Comment by csurfer** [comment]
@arinbjornk : I just installed the package using `pip3 install py-heat` and it seems to be working properly for me. Can you please check your classpath and other variables?

**Comment by arinbjornk** [comment]
@csurfer It starts fine but exits as it can't find some Python 3 libraries I import in the file, for example starmap.
