### ISSUE TITLE
Breaking change upstream in ppfrofile 

### ISSUE THREAD

**Issue by hinnefe2** [csurfer/pyheat#11]
Hello, thanks for making this neat tool!

It looks like [this commit](https://github.com/vpelletier/pprofile/commit/98a905a8dbcdfdfb24870fb4f6cbcdcb4ef41de6#diff-2e87482e90ea2abae8d317e3b930b31bL379) in `pprofile` changed the `Profile.file_dict` value to be a list instead of a single dictionary. This breaks the way `pyheat` parses the `Profile` object.

Running the existing tests gives this failure:
```
======================================================================
ERROR: test_pyheat_show (tests.pyheat_test.PyHeatTest)
Basic test to check pyheat class works end to end.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hhinnefeld/repos/pyheat-original/tests/pyheat_test.py", line 26, in test_pyheat_show
    self.pyheat.create_heatmap()
  File "/Users/hhinnefeld/repos/pyheat-original/pyheat/pyheat.py", line 48, in create_heatmap
    self.__fetch_heatmap_data_from_profile()
  File "/Users/hhinnefeld/repos/pyheat-original/pyheat/pyheat.py", line 100, in __fetch_heatmap_data_from_profile
    line_profiles = self.__get_line_profile_data()
  File "/Users/hhinnefeld/repos/pyheat-original/pyheat/pyheat.py", line 85, in __get_line_profile_data
    return self.line_profiler.file_dict[self.pyfile.path].line_dict
AttributeError: 'list' object has no attribute 'line_dict'

----------------------------------------------------------------------
```

I'll take a stab at fixing this myself, if that's alright.

**Comment by aktivkohle** [comment]
I just installed pyheat with pip and got this exact same error, if the fix fixes it would be good if it were merged. In the mean time will see if I can install @hinnefe2 's branch.

**Comment by aktivkohle** [comment]
Ok, I cloned the repo https://github.com/hinnefe2/pyheat , changed to branch fix-for-upstream-pprofile-changes locally and pip installed from the local directory and the error went away. Thanks! Unless something else gets broken by this, should probably be merged.

**Comment by csurfer** [comment]
@hinnefe2 's PR https://github.com/csurfer/pyheat/pull/12 fixes this.
