### ISSUE TITLE
Feature Request: Code text colour inversion 

### ISSUE THREAD

**Issue by thundergolfer** [csurfer/pyheat#5]
When the 'heat' gets too hot, and the highlight goes a dark maroon, black text is hardly visible. There should be some threshold that inverts text colour when the 'heat' goes to high (and thus the highlight gets too dark).

**Comment by csurfer** [comment]
@thundergolfer : Will include it soon.

**Comment by csurfer** [comment]
@thundergolfer : This issue has been fixed. It will become available in the next version of the PyPi package but until then you can set up the tool directly from repository clone for your purposes which has the fixed version.
