### ISSUE TITLE
Integration with Jupyter Notebooks

### ISSUE THREAD

**Issue by ozroc** [csurfer/pyheat#7]
It would be really cool to integrate this within Jupyter notebooks through a magic command:

![image](https://cloud.githubusercontent.com/assets/5380146/23066606/c313a878-f51b-11e6-82fd-72c8e69df41a.png)

**Comment by ozroc** [comment]
Here you are my first try:

[https://gist.github.com/ozroc/6dbaa286baab19273373ed05d9cf7629](url)

**Comment by csurfer** [comment]
Finally got around to it. https://github.com/csurfer/pyheatmagic
