### ISSUE TITLE
Python file to be run should be a mandatory positional argument, not an optional one

### ISSUE THREAD

**Issue by ozroc** [csurfer/pyheat#8]
`pyheat --pyfile <path_to_python_file>`

should simply be:

`pyheat <path_to_python_file>`

Additionally, it could be great to support output to a file:

`pyheat --out outpath.png <path_to_python_file>`

**Comment by csurfer** [comment]
**[First Part]** 
It is indeed mandatory. The pypi package is still on 0.0.1 and doesn't have some of the fixes done after it which will be picked in the next versions. The fixes I am talking about which are already merged are :
* Capability to import the Pyheat class from module.
* Inversion of the text color for the darker shades of the spectrum.

You can find these by installing the package directly from the github repo and not pip. Now if you type in `pyheat` it prints out help as to what a valid command is. I am hoping to keep this the same, that is with the `--pyfile` argument for better read.

**[Second Part]**
`--out` is definitely a great suggestion. Will fix it and pick it up for the next release.

**Comment by ozroc** [comment]
As usual in posix conventions I see more standard to leave the mandatory argument as a positional argument and not as an option. The only thing you get with that is forcing the user to always write --pyfile which is unnecessary...
